name: Simple Workflow

on: 
    workflow_dispatch:
        inputs:
          user_data:
            description: 'User Data'     
            required: true
            default: 'write something'
          tags:
            description: 'Test input user data'      

jobs:

    TIMESTAMP:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: 1.1.1 UPLOADING FILE maon.py
          run: |
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py
        - name: 1.1.2 UPLOADING FILE user_data.txt
          run: |
            echo '${{ github.event.inputs.user_data }}' >> ./.github/actions/action_1.2/user_data.txt
        - name: 1.1.3 PRINT USER DATA
          run: |
            echo " User Data: ${{ github.event.inputs.user_data }}"
        - name: 1.2 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2
        - name: 1.3 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
            name: output.txt
            path: /home/runner/work/devops-school/devops-school/output.txt
